### ISSUE TITLE
Cannot figure out how to invoke gitVersion() from Kotlin DSL

### ISSUE THREAD

**Issue by awesometown** [palantir/gradle-git-version#105]
I'm in the process of converting our build scripts to use the Kotlin DSL and where previously I could just invoke `gitVersion()` from my Groovy script, I can't figure out the equivalent in Kotlin.

I'm applying the plugin with:

```
plugins {
    id("com.palantir.git-version") version "0.12.0-rc2"
}
```

In groovy, it'd then just call `gitVersion()` but here I get "Unresolved reference: gitVersion"

Apologies that this isn't really an issue with the `gradle-git-version` plugin itself, but this is the only plugin I'm using that "adds ... methods to the target project" and I've been completely unable to find other examples of how to access those.

**Comment by matfax** [comment]
I'm facing the same issue.

**Comment by matfax** [comment]
I figured it out. Try this in your root config:

```Kotlin
plugins {
    id("com.palantir.git-version") version "0.12.0-rc2"
}

allprojects {
    apply(plugin = "com.palantir.git-version")

    version = (extensions.extraProperties.get("gitVersion") as? Closure<*>)?.call() ?: "dirty"
}

// For testing
tasks.create("printVersionName") {
    doLast { println(version) }
}
```

**Comment by awesometown** [comment]
Hmm... does that actually get you a version? I just end up with a reference to the plugin itself (eg. `com.palantir.gradle.gitversion.GitVersionPlugin$1@68a795c0`).

**Comment by matfax** [comment]
@awesometown You are right, that was just the reference object. I fixed and updated it accordingly. I have to admit; now it looks more of a workaround since a cast is necessary.

**Comment by awesometown** [comment]
That worked! Thanks!

I'd agree, it's not super pretty, but this has been the last blocker for getting our scripts converted to Kotlin, so I'll take it :)

**Comment by mindhaq** [comment]
This not only "not super pretty", this is ridicously ugly. I'm not sure gradle and its ecosystem is really as mature as I'd like to have it.

**Comment by timyates** [comment]
I believe you can also do (at least with Gradle 5.1):

```kotlin
val gitVersion: groovy.lang.Closure<*> by extra

tasks.register("proofOfConcept") {
    doLast {
        println(gitVersion.call())
    }
}
```

**Comment by markgitset** [comment]
You shouldn't need the extra `.call()` either (at least as of Gradle 5.6).
```kotlin
val gitVersion: groovy.lang.Closure<*> by extra
version = gitVersion()
```
It could still be better, but at least it's no longer "ridiculously ugly" :)

**Comment by sean-abbott** [comment]
The above worked for me (when inside the allprojects or subprojects blocks, anyway), but can we please add it to the docs? I had no way to work it out on my own.

Corollary question though. How would you do the details when you're using a * from the closture?
