### ISSUE TITLE
Add support for long format on all builds.

### ISSUE THREAD

**Issue by MicahZoltu** [palantir/gradle-git-version#16]
I would like to be able to always have the long format for my version.  Right now, if I am on a tag then the version is named after the tag.  If I am not on a tag a suffix is added.  I would like to be able to always have the suffix, regardless of whether I am on a tag or not.

This behavior can be achieved via `setLong` on the JGit `DescribeCommand`.

**Comment by markelliot** [comment]
We now produce a VersionDetails object that can be used to produce long-form descriptions as desired.
