### ISSUE TITLE
Document usage with kotlin dsl

### ISSUE THREAD

**Issue by mhmmerle** [palantir/gradle-git-version#188]
## What happened?

I could not find documentation how to use the functions added by this plugin with kotlin dsl.

## What did you want to happen?

Find in the README something like the following:
```
val gitVersion: groovy.lang.Closure<String> by extra
version = gitVersion(mapOf ("prefix" to "v-"))
```

**Comment by up-to-you** [comment]
I think that the Plugin can easily add convenient Kotlin support by implementing method like this:
`fun getVersionDetails(): VersionDetails = (extra["versionDetails"] as groovy.lang.Closure<*>)() as VersionDetails`

**Comment by ferozco** [comment]
@mhmmerle @up-to-you I'm not very familiar with kotlin, would either of you be willing to push up a PR with the changes that you'd like and then I'll be happy to review them

**Comment by xenoterracide** [comment]
kotlin is pretty easy to support, it's basically exporting a java API, you don't actually have to write it in kotlin....

**Comment by ferozco** [comment]
@xenoterracide I'm not suggesting that it would be difficult, I just would rather someone with experience writing kotlin/using kotlin buildscripts contribute the documentation for using the plugin. Especially since it seems like there are different approaches being suggested in this thread. Perhaps you would be willing to help us out?

**Comment by xenoterracide** [comment]
well, I would suggest both documentation, but also a kotlin DSL, which probably means not using, or at least not requiring groovy closures. Been a bit since I worked on a plugin though, if you want to expose a kotlin dsl I can try adding it to my list of things to do. just for a 3rd way (for anyone that finds this)

```kotlin
val versionDetails: groovy.lang.Closure<VersionDetails> by extra

springBoot {
  buildInfo {
    properties {
      val details = versionDetails()
      additional = mapOf<String, Any>(
        "gitHash" to details.gitHash,
        "gitHashFull" to details.gitHashFull,
        "lastTag" to details.lastTag,
        "commitDistance" to details.commitDistance,
        "isCleanTag" to details.isCleanTag
      )
    }
  }
}
```

**Comment by sean-abbott** [comment]
I'm brand new to both kotlin and gradle, I'm trying to use this from a kotlin build file.

I tried adding `val gitVersion: groovy.lang.Closure<GitVersion> by extra`* to my build.gradle.kts file, but it keeps complaining 
```
Script compilation error:

  Line 4: val gitVersion: groovy.lang.Closure<GitVersion> by extra
                                              ^ Unresolved reference: GitVersion
```

* I tried it with gitVersion in the Closure thing as well.

So I guess I don't know where to properly put this or call it?

**Comment by sschuberth** [comment]
@sean-abbott you should either use

    val gitVersion: groovy.lang.Closure<String> by extra
    version = gitVersion()

or

    val versionDetails: groovy.lang.Closure<com.palantir.gradle.gitversion.VersionDetails> by extra
    version = versionDetails().version

**Comment by jorge-lavin** [comment]
@sschuberth  I can't make it work:

```
e: xxx\shared.gradle.kts:6:49: Unresolved reference: palantir
```

In `build.gradle.kts`:

```
plugins {
    java
    id("com.palantir.git-version") version "0.12.0-rc2"
}

group = "com.lavinj87"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    //testImplementation("junit", "junit", "4.12")
}

configure<JavaPluginConvention> {
    sourceCompatibility = JavaVersion.VERSION_1_8
}


apply(from = "shared.gradle.kts")
```

In `shared.gradle.kts`:

```
tasks.register("writeVersionFile") {
    group = "build"
    description = "Writes the version file"
    val folder = project.file("src/main/resources");

   val versionDetails: groovy.lang.Closure<com.palantir.gradle.gitversion.VersionDetails> by extra
   val details = versionDetails()

    if(!folder.exists()){
        folder.mkdirs()
    }

    val props = project.file("src/main/resources/version.properties")
    props.delete()

   props.appendText("version=" + project.version + "\n")
   props.appendText("version=" + details.version + "\n")
   props.appendText("commit=" + details.gitHashFull + "\n")
   props.appendText("branch=" + details.branchName)
}
```

**Comment by sschuberth** [comment]
Just guessing (as I stopped using this plugin): Maybe moving

> val versionDetails: groovy.lang.Closure<com.palantir.gradle.gitversion.VersionDetails> by extra

out of the task helps, or writing `project.extra` instead of just `extra`, as tasks might have their own extra properties?
