### ISSUE TITLE
Allow users to get commit count

### ISSUE THREAD

**Issue by michael-yx-wu** [palantir/gradle-git-version#19]
Currently gitVersion() just returns a string, but it could be useful if it returned an object that allowed you to get the commit count, hash, tag, etc. Additionally, it might be good to allow users to get commit count since latest tag or total commit count.

**Comment by markelliot** [comment]
Feel free to use flexversion if you'd like something more featureful, the desire here is to have a simple, reliable, and no-configuration approach to getting versions that match what `git describe –t` would return.

**Comment by michael-yx-wu** [comment]
Okay, closing out!
