### ISSUE TITLE
Search parent directories for .git

### ISSUE THREAD

**Issue by sfackler** [palantir/gradle-git-version#23]
The plugin currently expects the .git directory to be in the project root, but git itself will search up through parent directories.

**Comment by markelliot** [comment]
This uses jgit under the covers and jgit doesn't presently support this functionality (https://issues.apache.org/jira/browse/SCM-806), though it could be implemented just in this plugin, I suppose. 

Do you have a git repo with multiple independent root projects, or are you just looking to call `gitVersion()` explicitly from a subproject?

If the latter, it's likely more efficient to set the version in an `allprojects` block in the root project and then use `project.version` anywhere you need the version in a subproject.

**Comment by sfackler** [comment]
This particular project is primarily non-Java, and has a subdirectory containing the source for a JAR that talks to the main project through JNI. It feels a bit cleaner to me to isolate Gradle to the subdirectory with the Java stuff since the rest of the project doesn't care about it.

**Comment by markelliot** [comment]
Cool, happy to take a contribution, might eventually get to this, but probably not in the next few weeks.

**Comment by jmcampanini** [comment]
let me know if this PR works.
