### ISSUE TITLE
Returns "unspecified" on one repo

### ISSUE THREAD

**Issue by zewt** [palantir/gradle-git-version#25]
This works on two repositories, but on a third, always gives "unspecified".  It's finding the repository, and git describe returns a tag/hash normally.

I'm not sure how to troubleshoot this (it's a private repository).  I can see that it's finding .git and reading it, and if I copy the not-working project inside the working repository it does work, so it does seem to be something about the repository that it doesn't like.  I'm not familiar with git internals to dig into it...

**Comment by markelliot** [comment]
Could you describe the outputs of `git describe --tags` and `git describe --all`?

**Comment by zewt** [comment]
git describe --tags
testing-4-ge4314f5
git describe --all
heads/gradle

I did notice a problem earlier, that it won't work if there are no tags (eg. it doesn't mimic the --always flag of git describe), so I created a dummy tag in each repository.

**Comment by markelliot** [comment]
Hm, the only thing I can imagine here is that jgit is crashing or otherwise erroring on your repo, I'm not really doing anything special here. Without a sample failing repo not much more I can do to debug unfortunately.

**Comment by zewt** [comment]
I tried a different plugin that also uses JGit and I get various errors (like "Missing unknown (hash)", https://www.eclipse.org/forums/index.php/t/847612/).  I gave up and switched over to just doing an exec of git.

**Comment by arumlv** [comment]
only for info, maybe someone will get the same error,
please check spelling gitVersion() not getVersion()
should be
version gitVersion()

gradle allow
version getVersion()

as a result,
> Task :printVersion
unspecified
