### ISSUE TITLE
Plugin with id 'com.palantir.git-version' not found, while using internally hosted artifactory.

### ISSUE THREAD

**Issue by ravikanthc** [palantir/gradle-git-version#31]
I would like to use Gradle Git-Version 0.4.2

I am trying to use the plugin from internally hosted artifactory instead of https://plugins.gradle.org/m2/ as described in the build script snippet for use in all Gradle versions as per the note at https://plugins.gradle.org/plugin/com.palantir.git-version/0.4.2

Step 1: I have loaded the plugin jar to internal artifactory.
https://testrepo.com/artifactory/gradle-plugin/gradle/plugin/com/palantir/gradle/gitversion/gradle-git-version/0.4.2/gradle-git-version-0.4.2.jar

Step 2:
In my gradle.properties I have

```
artifactory_3PpluginsUrl=https://testrepo.com/artifactory/gradle-plugin
```

In my build.gradle I have

```
buildscript {
  repositories {
    maven {
      url "${artifactory_3PpluginsUrl}" 
    }
  }
  dependencies {
    classpath "gradle.plugin.com.palantir.gradle.gitversion:gradle-git-version:0.4.2"
  }
}
apply plugin: "com.palantir.git-version"
```

Step 3:
Upon execution, I get

```
* What went wrong:
A problem occurred evaluating root project 'EvalProjUtil'.
> Plugin with id 'com.palantir.git-version' not found.
```

I believe it is downloading the dependency

```
…
Unable to locate local Maven repository.
Download https://testrepo.com/artifactory/gradle-plugin/gradle/plugin/com/palantir/gradle/gitversion/gradle-git-version/0.4.2/gradle-git-version-0.4.2.pom
Download https://testrepo.com/artifactory/gradle-plugin/gradle/plugin/com/palantir/gradle/gitversion/gradle-git-version/0.4.2/gradle-git-version-0.4.2.jar
Compiling build file 'C:\codeBase\EvalProjUtil\build.gradle' using BuildScriptTransformer.
```

**Comment by ravikanthc** [comment]
Please ignore, this is not a plugin issue. The uploaded jar was corrupted. it was missing the class files.

**Comment by ravikanthc** [comment]
Although plugin is getting resolved, I am getting. null object/unspecified on gitVersion() and eventually the below error. 
- What went wrong:
  A problem occurred evaluating root project 'EvalProjUtil'.
  > Cannot get property 'lastTag' on null object

Code snippet: 
    def details = versionDetails()
    def tag = details.lastTag

However if i use the Plugins block the build executes fine, plugin returns... version: v1.0.dirty. Is there something I am missing, Are there any additional steps to follow before the plugins is consumed in addition to the what is specified at https://plugins.gradle.org/plugin/com.palantir.git-version/0.4.2

**Comment by markelliot** [comment]
How did you obtain the maven artifact?

**Comment by ravikanthc** [comment]
I have used the jar file(from $User_Home.gradle\caches\modules-2\files-2.1~) that was downloaded when I tried the plugins block. And manually uploaded it to the Maven

**Comment by markelliot** [comment]
How did you make the POM file?

**Comment by ravikanthc** [comment]
i used the POM file that was downloaded as well

**Comment by markelliot** [comment]
I think you might have more luck grabbing the artifacts from here: https://jcenter.bintray.com/com/palantir/gradle/gitversion/gradle-git-version/0.4.2/ (including the POM file)

Which would let you refer to this as:

```
buildscript {
    repositories { ... }
    dependencies {
        classpath "com.palantir.gradle.gitversion:gradle-git-version:0.4.2"
    }
}
apply plugin: "com.palantir.git-version"
```

**Comment by ravikanthc** [comment]
Thank you! that worked!

So what is the difference that made it to work now ? I realize you have removed gradle.plugins in the beginning of the group id for class path and to accomodate the same i removed the same from directory structure in our internal maven repo.

**Comment by markelliot** [comment]
I'm not quite sure how the Gradle maven repos are set up, and I'm also not sure how you grabbed the POM files. I suspect some redirects are at play. The thing published to Bintray is a real maven publication with coordinates that match the publication, and suspect that's the primary thing.
