### ISSUE TITLE
gitHash returns 'unspecified'

### ISSUE THREAD

**Issue by rocketraman** [palantir/gradle-git-version#40]
I have a git repository. At the moment it has no tags. I would still expect git hash to return the HEAD object hash, but instead it returns 'unspecified'.

**Comment by hxu** [comment]
I ran into this same issue on a new project, and found it difficult to figure out why it was giving me unspecified.  I think it would be helpful for the task to log a `WARN` or something if it encounters this case.

**Comment by wtanaka** [comment]
another approach: https://github.com/palantir/gradle-git-version/pull/53

**Comment by uschi2000** [comment]
fixed by #53
