### ISSUE TITLE
Add branchName to VersionDetails

### ISSUE THREAD

**Issue by jared2501** [palantir/gradle-git-version#42]
Which is an `optional<string>`

**Comment by jared2501** [comment]
@markelliot - sound reasonable?

**Comment by markelliot** [comment]
Yeah

**Comment by jared2501** [comment]
@markelliot - sweet! checkout https://github.com/palantir/gradle-git-version/pull/43

**Comment by jared2501** [comment]
@markelliot - any chance of a release with this in it? need it for a project
