### ISSUE TITLE
Change plugin to match behavior of "git describe --first-parent"

### ISSUE THREAD

**Issue by nmiyake** [palantir/gradle-git-version#46]
Currently, the output of `gradle-git-version` matches the output of `git describe`. Although this is fine in the common case, it's often not the desired behavior if merge commits exist.

For example, consider the following case:

* Mainline branch has some tag (`1.0.0-dev`) and development is proceeding normally
* Some other branch (for example, `1.0.0-hotfix`) is merged into the mainline branch
* `gradle-git-version` is run on the mainline branch

In this scenario, we typically want the output to still be `1.0.0-dev-*`. However, because `git describe` returns the nearest ancestor tag, the merge causes `1.0.0-hotfix` to be found as a parent tag that is "closer" to the commit than `1.0.0-dev`, so you get `1.0.0-hotfix-*` instead.

The fix would be to match the behavior of `git describe --first-parent` instead -- this command only considers the first parent commit for merge commits, and would cause this to work correctly. I believe that this is almost always the desired behavior.

**Comment by nmiyake** [comment]
@uschi2000 @markelliot thoughts?

Unfortunately, JGit doesn't provide a great way to do this (see https://dev.eclipse.org/mhonarc/lists/jgit-dev/msg03017.html and http://stackoverflow.com/questions/33038224/how-to-call-git-show-first-parent-in-jgit).

I have a working implementation based on http://stackoverflow.com/questions/33038224/how-to-call-git-show-first-parent-in-jgit -- it involves defining a new class called `DescribeFirstParentCommand` which is basically a copy of `org.eclipse.jgit.api.DescribeCommand`, except that it applies a `FirstParentFilter` to the `RevWalk` (unfortunately, even though `DescribeCommand` is non-final, the internal `RevWalk` is not accessible so there's no clean way to apply this behavior externally). Can put it up as a PR, but would like to see if you guys would be open to this first.

**Comment by uschi2000** [comment]
I think that's reasonable *if* you have such merges. I would hope that they are rare?

**Comment by nmiyake** [comment]
I think it depends largely on the repository -- I believe this is a pretty standard procedure in GitFlow, right?

**Comment by nmiyake** [comment]
@bmoylan for SA as well.

**Comment by markelliot** [comment]
Maybe we should just make this thing shell out to git and call it a day?

**Comment by nmiyake** [comment]
I'd be fine with that as well (and that's what gödel does). Obviously introduces a dependency around the host system having the `git` command and it being callable, but I think it's generally a safe assumption. However, understand why having a pure Java implementation could be preferable as well.

Opened https://github.com/palantir/gradle-git-version/pull/48 as a pure Java fix for this for consideration.
