### ISSUE TITLE
FR: isRelease boolean on VersionDetails

### ISSUE THREAD

**Issue by iamdanfox** [palantir/gradle-git-version#57]
I frequently see logic in other gradle files that is conditional on whether the project is 'released' or still 'under development':

```groovy
def isRelease = (project.version.toString() ==~ /[0-9]+(\.[0-9]+)+((-(beta|rc)[0-9]{1,2})(\.[0-9])?)?/)
dockerPush.onlyIf { isRelease }
```

To avoid duplicating this regex, let's add a convenience boolean to the VersionDetails object, allowing us to write: 

```groovy
dockerPush.onlyIf { gitVersion().isRelease }
```

**Comment by uschi2000** [comment]
+1
