### ISSUE TITLE
Handle "v" in version tags

### ISSUE THREAD

**Issue by maxidorius** [palantir/gradle-git-version#66]
Many projects, and recommended versionning model of Github, prepend their version git tags with a `v`, so something like `v1.2.3`, but this tag should not present in artifacts, especially anything sent to a Maven repository.

Could it be possible that `gitVersion()` does NOT return the prepended `v`?

**Comment by uschi2000** [comment]
We specifically recommend against that v prefix for our tags (by convention, it was important for us to just lick one standard and stick with it), so I'm afraid we are not going to add this, sorry.

Sent from Email+ secured by MobileIron

-------- Original Message --------

**Comment by maxidorius** [comment]
@uschi2000 what are the reasons you recommend against it? see if that could make a difference

**Comment by uschi2000** [comment]
There is no reason other than "pick *a* convention and stick to it". We picked "no v" at some point in the past for no particular reason other than maybe "it is one character shorter and the v does not any extra information".

**Comment by maxidorius** [comment]
Fair enough, thanks for the quick follow up!
