### ISSUE TITLE
GitHash should allow non-abbreviation 

### ISSUE THREAD

**Issue by jiahuijiang** [palantir/gradle-git-version#67]
Right now gitHash is hard-coded to return a 10 character abbreviation. But this should be allowed to be configured with a default.
This is useful when we want to convert it back to an ObjectID
https://github.com/palantir/gradle-git-version/blob/develop/src/main/groovy/com/palantir/gradle/gitversion/GitVersionPlugin.groovy#L104

**Comment by uschi2000** [comment]
What's the use case for this?

Sent from Email+ secured by MobileIron

-------- Original Message --------

**Comment by jiahuijiang** [comment]
In transforms's renderShrinkwrap task, we now call out to Shrinkwrap service with the commitHash. And Shrinkwrap service checks whether this commitHash is the latest to decide whether to render the shrinkwrap file or not. Without the full commitHash, we can only check whether the latest commitHash starts with the commitHash gradle-git-version returns, which looks very hacky.
There are other workarounds but think this is a simple and intuitive feature to support.

**Comment by uschi2000** [comment]
This is a pretty specific use case and unrelated to the goal of this plugin. I think I'd prefer you copy the 3-4 lines of JGit code into your project if possible.

**Comment by jiahuijiang** [comment]
Okay makes sense since this is purely for generating a version not a Git helper plugin. Closing now

**Comment by matthew-dailey** [comment]
I just ran into this limitation as well.  My team normally records full git hashes for snapshot artifacts (like RPMs), so being able to have one-to-one matching with the full git hash from this plugin would be really helpful.

A change like this could be made in a backwards-compatible way, too.  One solution would be to add a new field like `versionDetails().gitHashFull` to return the full hash, then `versionDetails().gitHash` would continue returning the 10-character hash.

Does that sound like a valid solution?  I could make the PR for it

**Comment by uschi2000** [comment]
Yep, I'm fine with that.
