### ISSUE TITLE
Use git-describe to generate version

### ISSUE THREAD

**Issue by esword** [palantir/gradle-git-version#704]
## What happened?
The plugin uses some complex, looping logic to calculate the describe string which forms the basis for the version (See the Git.describe method).  This was to support older versions of git (<1.8.4) that did not have all the options that git-describe needed to produce the proper version string directly.

## What did you want to happen?
 Now that the features have been git-describe for 10+ years and the codebase has shifted to only native git usage, we can replace the custom code with a single call to git describe:

git describe --tags --always --abbrev=7 --first-parent --match=[prefix]* HEAD

**Comment by ash211** [comment]
@esword can this issue be closed?

**Comment by esword** [comment]
Yes
