### ISSUE TITLE
Unable to use plugin per readme

### ISSUE THREAD

**Issue by ericanderson** [palantir/gradle-git-version#71]
Can't use:
```
plugins {
    id 'com.palantir.git-version' version '<current version>'
}
```

Have to use the oldschool `buildscript {}` method.

**Comment by vincentdaniel** [comment]
fyi, both ways to include the plugin in your build script are described here: https://plugins.gradle.org/plugin/com.palantir.git-version

**Comment by ericanderson** [comment]
Don’t need it any more but I’m glad to see it publishing right.
