### ISSUE TITLE
Strict prefix regex

### ISSUE THREAD

**Issue by PawelJ-PL** [palantir/gradle-git-version#72]
Hi,

I would ask You, whether it's possible to change prefix regex to less strict one. I'm using following tags in my project: app_name__x.y.z (where x.y.z is version). I don't like to change my tags schema, because my pipeline relays on it, so I'm unable to use this plugin.

**Comment by uschi2000** [comment]
I think we're unlikely to change it because we want to enforce a consistent tagging and versioning scheme for our products and libraries.

**Comment by DiggidyDave** [comment]
v1.2.3 is pretty idiomatic.  It looks like we aren't able to use "v" as a prefix for the base version?

**Comment by uschi2000** [comment]
Correct.

**Comment by DiggidyDave** [comment]
Thanks.

**Comment by iamdanfox** [comment]
Closing out as this is an intentional design decision of the `gradle-git-version` plugin that enforces valuable consistency in internal palantir repos.
